### ISSUE TITLE
CredentialsError on first Client() logon

### ISSUE THREAD

**Issue by palewire** [oittaa/gcp-storage-emulator#178]
Seeing stuff like this. How do I handle the credentials for my first login?

```
>>> from google.cloud import storage
>>> storage.Client()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/palewire/.local/share/virtualenvs/bln-rP4rNvCf/lib/python3.9/site-packages/google/cloud/storage/client.py", line 124, in __init__
    super(Client, self).__init__(
  File "/home/palewire/.local/share/virtualenvs/bln-rP4rNvCf/lib/python3.9/site-packages/google/cloud/client/__init__.py", line 320, in __init__
    _ClientProjectMixin.__init__(self, project=project, credentials=credentials)
  File "/home/palewire/.local/share/virtualenvs/bln-rP4rNvCf/lib/python3.9/site-packages/google/cloud/client/__init__.py", line 268, in __init__
    project = self._determine_default(project)
  File "/home/palewire/.local/share/virtualenvs/bln-rP4rNvCf/lib/python3.9/site-packages/google/cloud/client/__init__.py", line 287, in _determine_default
    return _determine_default_project(project)
  File "/home/palewire/.local/share/virtualenvs/bln-rP4rNvCf/lib/python3.9/site-packages/google/cloud/_helpers/__init__.py", line 152, in _determine_default_project
    _, project = google.auth.default()
  File "/home/palewire/.local/share/virtualenvs/bln-rP4rNvCf/lib/python3.9/site-packages/google/auth/_default.py", line 579, in default
    raise exceptions.DefaultCredentialsError(_HELP_MESSAGE)
google.auth.exceptions.DefaultCredentialsError: Could not automatically determine credentials. Please set GOOGLE_APPLICATION_CREDENTIALS or explicitly create credentials and re-run the application. For more information, please see https://cloud.google.com/docs/authentication/getting-started
```

**Comment by oittaa** [comment]
One option is to define `STORAGE_EMULATOR_HOST` env variable, which disables real credentials, like in the examples.

**Comment by palewire** [comment]
I was using the credentials, so that wasn't the problem. It turned out the issue was that the legacy project I'm retrofitting had a version of google-cloud-storage was so old it didn't support that environment variable. An upgrade fixed it.
