### ISSUE TITLE
`TypeError` when uploading binary files

### ISSUE THREAD

**Issue by Edholm** [oittaa/gcp-storage-emulator#85]
I don't know if I'm doing something wrong when uploading binary files, but I get this error:

```
Exception occurred during processing of request from ('172.17.0.1', 55522)
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/socketserver.py", line 316, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/local/lib/python3.9/socketserver.py", line 347, in process_request
    self.finish_request(request, client_address)
  File "/usr/local/lib/python3.9/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/lib/python3.9/site-packages/gcp_storage_emulator/server.py", line 348, in __init__
    super().__init__(*args, **kwargs)
  File "/usr/local/lib/python3.9/socketserver.py", line 747, in __init__
    self.handle()
  File "/usr/local/lib/python3.9/http/server.py", line 427, in handle
    self.handle_one_request()
  File "/usr/local/lib/python3.9/http/server.py", line 415, in handle_one_request
    method()
  File "/usr/local/lib/python3.9/site-packages/gcp_storage_emulator/server.py", line 356, in do_POST
    router.handle(POST)
  File "/usr/local/lib/python3.9/site-packages/gcp_storage_emulator/server.py", line 334, in handle
    raise e
  File "/usr/local/lib/python3.9/site-packages/gcp_storage_emulator/server.py", line 325, in handle
    handler(request, response, self._request_handler.storage)
  File "/usr/local/lib/python3.9/site-packages/gcp_storage_emulator/handlers/objects.py", line 230, in insert
    return _create_resumable_upload(request, response, storage)
  File "/usr/local/lib/python3.9/site-packages/gcp_storage_emulator/handlers/objects.py", line 176, in _create_resumable_upload
    request.data["name"],
TypeError: byte indices must be integers or slices, not str
```

This was the URL from the logs (URL decoded):
```
http://0.0.0.0:8080/upload/storage/v1/b/logs/o?alt=json&name=Log1/210719-112358Z-apabepa/Log1-210719-112358Z-apabepa.lcmlog&prettyPrint=false&projection=full&uploadType=resumable&upload_id=logs:Log1/210719-112358Z-apabepa/Log1-210719-112358Z-apabepa.lcmlog:2021-09-16+11:16:33.090102
```

The file was some roughly 100-200MB iirc.

Something you've seen before?

**Comment by oittaa** [comment]
The whole resumable upload function is a bit of a hack. Anything over 100MB probably won't work. I'm using this mostly for testing so the limit isn't reached basically ever, but I'd be more than happy to receive a pull request for proper resumable uploads.

**Comment by oittaa** [comment]
The whole file is still loaded in the memory at times. You might run out of memory while handling extremely large files, but any regular computer should handle your 200MB files now.
